spring.application.name=places-booking-service
server.port=${SERVER_PORT:8082}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/places}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:places}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:places}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=booking_schema
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.default-schema=booking_schema
spring.flyway.schemas=booking_schema
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info,prometheus
